#!/bin/bash

# Raspberry Pi Network Troubleshooting and Fix Script
# Run this on the Pi to diagnose and fix network connectivity issues

echo "=== Raspberry Pi Network Diagnostics and Fix ==="
echo "Date: $(date)"
echo "Hostname: $(hostname)"
echo "Kernel: $(uname -r)"
echo

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to test connectivity
test_connectivity() {
    local host=$1
    local description=$2
    
    if ping -c 1 -W 5 "$host" >/dev/null 2>&1; then
        print_success "$description: OK"
        return 0
    else
        print_error "$description: FAILED"
        return 1
    fi
}

# Function to test DNS resolution
test_dns() {
    local hostname=$1
    local description=$2
    
    if nslookup "$hostname" >/dev/null 2>&1; then
        print_success "DNS resolution for $description: OK"
        return 0
    else
        print_error "DNS resolution for $description: FAILED"
        return 1
    fi
}

echo "=== STEP 1: Current Network Configuration ==="
print_status "Network interfaces:"
ip addr show | grep -E "^[0-9]+:|inet "
echo

print_status "Routing table:"
ip route show
echo

print_status "DNS configuration:"
cat /etc/resolv.conf
echo

print_status "WiFi status:"
if command -v iwconfig >/dev/null 2>&1; then
    iwconfig 2>/dev/null | grep -E "ESSID|Signal|Bit Rate" || echo "No wireless interfaces found"
else
    echo "iwconfig not available"
fi
echo

echo "=== STEP 2: Connectivity Tests ==="
print_status "Testing basic connectivity..."

# Test local connectivity
test_connectivity "127.0.0.1" "Localhost"
test_connectivity "192.168.4.1" "Pi self (hotspot IP)"
test_connectivity "192.168.4.2" "Ground station (expected)"

# Test gateway
GATEWAY=$(ip route | grep default | awk '{print $3}' | head -1)
if [ -n "$GATEWAY" ]; then
    test_connectivity "$GATEWAY" "Default gateway ($GATEWAY)"
else
    print_warning "No default gateway found"
fi

# Test external connectivity
test_connectivity "8.8.8.8" "Google DNS (8.8.8.8)"
test_connectivity "1.1.1.1" "Cloudflare DNS (1.1.1.1)"
echo

echo "=== STEP 3: DNS Resolution Tests ==="
print_status "Testing DNS resolution..."
test_dns "google.com" "Google"
test_dns "deb.debian.org" "Debian repository"
test_dns "archive.raspberrypi.org" "Raspberry Pi repository"
test_dns "security.debian.org" "Debian security repository"
echo

echo "=== STEP 4: Automatic Fixes ==="

# Fix 1: Update DNS servers
print_status "Applying DNS fixes..."
if ! grep -q "8.8.8.8" /etc/resolv.conf; then
    print_status "Backing up current resolv.conf"
    sudo cp /etc/resolv.conf /etc/resolv.conf.backup
    
    print_status "Adding Google DNS servers"
    {
        echo "# Generated by pi_network_fix.sh"
        echo "nameserver 8.8.8.8"
        echo "nameserver 8.8.4.4"
        echo "nameserver 1.1.1.1"
    } | sudo tee /etc/resolv.conf.new > /dev/null
    
    sudo mv /etc/resolv.conf.new /etc/resolv.conf
    print_success "DNS servers updated"
else
    print_success "DNS servers already configured"
fi

# Fix 2: Restart network services
print_status "Restarting network services..."
sudo systemctl restart systemd-resolved 2>/dev/null || print_warning "systemd-resolved not available"
sudo systemctl restart networking 2>/dev/null || print_warning "networking service restart failed"
sudo systemctl restart dhcpcd 2>/dev/null || print_warning "dhcpcd service restart failed"

# Wait for network to stabilize
print_status "Waiting for network to stabilize..."
sleep 5

# Fix 3: Test package manager
print_status "Testing package manager connectivity..."
if sudo apt update >/dev/null 2>&1; then
    print_success "Package manager connectivity restored"
else
    print_warning "Package manager still has issues, trying alternative sources"
    
    # Backup sources.list
    sudo cp /etc/apt/sources.list /etc/apt/sources.list.backup
    
    # Try alternative mirrors
    print_status "Configuring alternative package sources"
    {
        echo "# Alternative Debian sources - generated by pi_network_fix.sh"
        echo "deb http://mirror.ox.ac.uk/sites/archive.ubuntu.com/ubuntu/ bullseye main restricted universe multiverse"
        echo "deb http://mirror.ox.ac.uk/sites/archive.ubuntu.com/ubuntu/ bullseye-updates main restricted universe multiverse"
        echo "deb http://mirror.ox.ac.uk/sites/archive.ubuntu.com/ubuntu/ bullseye-security main restricted universe multiverse"
    } | sudo tee /etc/apt/sources.list.alt > /dev/null
    
    # Test alternative sources
    if sudo apt -o Dir::Etc::sourcelist=/etc/apt/sources.list.alt update >/dev/null 2>&1; then
        sudo mv /etc/apt/sources.list.alt /etc/apt/sources.list
        print_success "Alternative package sources configured"
    else
        print_error "Alternative sources also failed, keeping original"
        sudo rm -f /etc/apt/sources.list.alt
    fi
fi

echo
echo "=== STEP 5: Post-Fix Verification ==="
print_status "Re-testing connectivity after fixes..."

# Re-test DNS
test_dns "google.com" "Google (after fix)"
test_dns "deb.debian.org" "Debian repository (after fix)"

# Test package update
print_status "Testing package manager..."
if timeout 30 sudo apt update >/dev/null 2>&1; then
    print_success "Package manager working"
else
    print_warning "Package manager still has issues"
fi

echo
echo "=== STEP 6: WiFi Hotspot Configuration ==="
print_status "Checking WiFi hotspot configuration..."

# Check if hostapd is installed and configured
if command -v hostapd >/dev/null 2>&1; then
    print_success "hostapd is installed"
    
    if [ -f /etc/hostapd/hostapd.conf ]; then
        print_success "hostapd configuration exists"
        print_status "Current hotspot configuration:"
        grep -E "ssid=|channel=|wpa_passphrase=" /etc/hostapd/hostapd.conf 2>/dev/null || echo "No configuration found"
    else
        print_warning "hostapd configuration missing"
        print_status "Creating basic hotspot configuration..."
        
        sudo tee /etc/hostapd/hostapd.conf > /dev/null << 'EOF'
interface=wlan0
driver=nl80211
ssid=DroneGroundStation
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=DroneControl123
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF
        print_success "Basic hotspot configuration created"
    fi
else
    print_warning "hostapd not installed"
    print_status "Installing hostapd and dnsmasq..."
    if sudo apt install -y hostapd dnsmasq >/dev/null 2>&1; then
        print_success "hostapd and dnsmasq installed"
    else
        print_error "Failed to install hostapd and dnsmasq"
    fi
fi

# Check dnsmasq configuration
if command -v dnsmasq >/dev/null 2>&1; then
    print_success "dnsmasq is installed"
    
    if [ -f /etc/dnsmasq.conf ] && grep -q "interface=wlan0" /etc/dnsmasq.conf; then
        print_success "dnsmasq configuration exists"
    else
        print_warning "dnsmasq configuration missing or incomplete"
        print_status "Adding basic dnsmasq configuration..."
        
        # Backup original
        sudo cp /etc/dnsmasq.conf /etc/dnsmasq.conf.backup 2>/dev/null
        
        # Add hotspot configuration
        {
            echo "# Drone Ground Station hotspot configuration"
            echo "interface=wlan0"
            echo "dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h"
            echo "domain=local"
            echo "address=/gw.local/192.168.4.1"
        } | sudo tee -a /etc/dnsmasq.conf > /dev/null
        
        print_success "dnsmasq configuration updated"
    fi
fi

echo
echo "=== STEP 7: Service Status Check ==="
print_status "Checking critical services..."

services=("ssh" "networking" "dhcpcd" "hostapd" "dnsmasq")
for service in "${services[@]}"; do
    if systemctl is-active --quiet "$service"; then
        print_success "$service: running"
    else
        print_warning "$service: not running"
        print_status "Attempting to start $service..."
        if sudo systemctl start "$service" 2>/dev/null; then
            print_success "$service: started"
        else
            print_error "$service: failed to start"
        fi
    fi
done

echo
echo "=== STEP 8: System Information ==="
print_status "System resources:"
echo "CPU temperature: $(vcgencmd measure_temp 2>/dev/null || echo 'N/A')"
echo "Memory usage: $(free -h | grep Mem | awk '{print $3"/"$2}')"
echo "Disk usage: $(df -h / | tail -1 | awk '{print $3"/"$2" ("$5" used)"}')"
echo "Uptime: $(uptime -p 2>/dev/null || uptime)"

echo
echo "=== STEP 9: Recommendations ==="
print_status "Based on the diagnostics, here are the recommendations:"

if test_connectivity "8.8.8.8" "Final connectivity test" >/dev/null 2>&1; then
    print_success "✓ Internet connectivity is working"
    echo "  → You can proceed with package installations"
    echo "  → Run: sudo apt update && sudo apt upgrade"
else
    print_warning "✗ Internet connectivity still has issues"
    echo "  → Check physical network connections"
    echo "  → Verify router/modem settings"
    echo "  → Consider using ethernet connection temporarily"
fi

if systemctl is-active --quiet hostapd && systemctl is-active --quiet dnsmasq; then
    print_success "✓ WiFi hotspot services are running"
    echo "  → Laptop should be able to connect to 'DroneGroundStation'"
    echo "  → Password: DroneControl123"
else
    print_warning "✗ WiFi hotspot needs configuration"
    echo "  → Run: sudo systemctl enable hostapd dnsmasq"
    echo "  → Run: sudo systemctl start hostapd dnsmasq"
fi

echo
echo "=== STEP 10: Next Steps ==="
print_status "Immediate actions:"
echo "1. If internet is working: sudo apt update && sudo apt install -y python3-pip git"
echo "2. Create project directory: mkdir -p ~/drone_ground_station"
echo "3. Transfer files from laptop using SCP"
echo "4. Test camera: libcamera-hello --timeout 5000"
echo "5. Test UART: ls -la /dev/serial*"
echo
print_status "For detailed setup instructions, refer to REMOTE_SETUP_GUIDE.md"

echo
echo "=== Diagnostics Complete ==="
echo "Log saved to: /tmp/pi_network_diagnostics_$(date +%Y%m%d_%H%M%S).log"
echo "Run this script again after making changes to re-test."